Module6 task1
htmlacademy-ecmascript/1136803-taskmanager-12 pull request #8
Opened 2020-08-29 22:47 UTC by ildarjans

https://up.htmlacademy.ru/ecmascript/12/module/6

2020-08-30 17:31 UTC, Sergey-Rozhkov commented on src/mock/tasks.js
> +  return `${a}${b}`;
Для чего так ?

2020-08-30 17:32 UTC, Sergey-Rozhkov commented on src/presenter/task.js
> +    window.console.log(this._task);
Консольлог убрать

2020-08-30 17:33 UTC, Sergey-Rozhkov commented on src/presenter/task.js
> +        )
Абсолютно идентично
```suggestion
this._task.isArchive = !this._task.isArchive;
```

2020-08-30 17:34 UTC, Sergey-Rozhkov commented on src/presenter/task.js
> +        )
Сложно, Object.assign не создает новый объект, приходи на консультацию

2020-08-30 17:36 UTC, Sergey-Rozhkov commented on src/utils/common.js
> +  ];
Можно через [splice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice) в одну строку

2020-08-30 17:37 UTC, Sergey-Rozhkov commented on src/utils/filters.js
>      counter[`favorite`] += isFavorite;
isFavorite это разве не boolean ?

2020-08-30 21:46 UTC, ildarjans commented on src/mock/tasks.js
> +  return `${a}${b}`;
нужен было выдать какой id, чем не id? )

2020-08-30 21:56 UTC, ildarjans commented on src/utils/filters.js
>      counter[`favorite`] += isFavorite;
Boolean. Не очень явно? или так нельзя?

2020-08-30 21:59 UTC, ildarjans commented on src/presenter/task.js
> +        )
Я не увидел тут надобности создавать новый объект. На лету мутирую this._task и его же передают в функцию.

2020-08-30 22:01 UTC, ildarjans commented on src/presenter/task.js
> +        )
согласен

2020-08-30 22:05 UTC, ildarjans commented on src/presenter/task.js
> +        )
Только я тут объект this._task передают в функцию. Я ж не могу только одно поле передать..
Не понял твое предложение.

2020-08-31 12:22 UTC, Sergey-Rozhkov commented on src/view/task-edit-card.js
> +export default class TaskEditView extends Smart {
неверное название `TaskEditCardView`

2020-08-31 13:21 UTC, ildarjans commented
Вот эту функцию
```
  _favoriteClickHandler() {
    this._changeData(
        Object.assign(
            this._task,
            {
              isFavorite: !this._task.isFavorite
            }
        )
    );
  }
```

ты мне рекомендовал переписать в одну строку ... https://github.com/htmlacademy-ecmascript/1136803-taskmanager-12/pull/8#discussion_r479795628
Я так не могу сделать, т.к. this._changeData() ожидаем объект task.

2020-09-02 18:23 UTC, Sergey-Rozhkov requested changes
Остались замечания

2020-09-02 18:23 UTC, Sergey-Rozhkov commented on src/presenter/board.js
> +    // {id: presenter}
Зачем тут это ?

2020-09-02 18:23 UTC, Sergey-Rozhkov commented on src/presenter/board.js
> +    // TaskChangeHandlers
Удалить коментарий

2020-09-02 18:23 UTC, Sergey-Rozhkov commented on src/presenter/task.js
> +};
Может это в константы ?

2020-09-02 18:23 UTC, Sergey-Rozhkov commented on src/presenter/task.js
> +    // handlers
Удалить

2020-09-02 18:23 UTC, Sergey-Rozhkov commented on src/presenter/task.js
> +    }
```suggestion
    if (this._mode === Mode.DEFAULT) {
      replaceDOMElement(this._taskComponent, prevTaskComponent);
    } else if (this._mode === Mode.EDIT) {
      replaceDOMElement(this._taskFormComponent, prevTaskFormComponent);
    }
```
А ещё лучше через switch...case

2020-09-02 18:23 UTC, Sergey-Rozhkov commented on src/presenter/task.js
> +        )
Обсуждали это

2020-09-02 18:23 UTC, Sergey-Rozhkov commented on src/presenter/task.js
> +        )
```
this._task.isFavorite = !this._task.isFavorite;
```

2020-09-02 18:23 UTC, Sergey-Rozhkov commented on src/view/smart.js
> +    prevElement = null; // is it nessesary?
Удалить коментарий

2020-09-03 14:00 UTC, merged

2020-09-03 14:26 UTC, ildarjans commented on src/presenter/task.js
> +    // handlers
ты про коммент или    
 
```
this._taskComponent 
this._taskFormComponent
```
 
?